version: '3'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    restart: always
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wordpress_network

  wordpress:
    build:
      context: ./requirements/wordPress
    restart: always
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8080:9000"
    depends_on:
      - mariadb
    networks:
      - wordpress_network

  nginx:
    build:
      context: ./requirements/nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
      - mariadb
    networks:
      - wordpress_network 

networks:
  wordpress_network:
    driver: bridge


volumes:
  mariadb_data:
  wordpress_data:
  nginx_conf:
