version: "3.8"

services:
  nginx:	
    build: ./requirements/nginx
    ports: 443:443
    env_file: .env

  mariadb:
    build: ./requirements/mariadb
    env_file: .env

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
