version: '3'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    restart: always
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wordpress_network  # Ensure this matches the network name

  wordpress:
    build:
      context: ./requirements/wordPress
    restart: always
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8080:9000"
    depends_on:
      - mariadb
    networks:
      - wordpress_network  # Ensure this matches the network name

  nginx:
    build:
      context: ./requirements/nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - wordpress_network  # Ensure this matches the network name

networks:
  wordpress_network:
    driver: bridge


volumes:
  mariadb_data:
  wordpress_data:
  nginx_conf:
