version: '3'

services:

  nginx:
    build: ./requirements/nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress
      - mariadb
    networks:
      - my_network 

  wordpress:
    build: ./requirements/wordPress
    restart: always
    volumes:
      - wp_data:/var/www/html
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - my_network

  mariadb:
    build:  ./requirements/mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env
    networks:
      - my_network


networks:
  my_network:
    driver: bridge

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aappleto/data/wp_data
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aappleto/data/db_data

