version: '3'

services:

  nginx:
    build:
      context: ./requirements/nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
      - mariadb
    networks:
      - my_network 

  wordpress:
    build:
      context: ./requirements/wordPress
    restart: always
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - my_network

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    restart: always
    networks:
      - my_network
    volumes:
      - db:/var/lib/mysql
    env_file: .env

networks:
  my_network:
    driver: bridge

volumes:
  wordpress:
   name: wordpress
   driver: local
   driver_opts:
    device: /home/courinha/Desktop/42_Inception/srcs/wordpress
    o: bind
    type: none
  db:
   name: mariadb
   driver: local
   driver_opts:
    device: /home/courinha/Desktop/42_Inception/srcs/mariadb
    o: bind
    type: none
